"""init master

Revision ID: 6da0a94fad8f
Revises: 
Create Date: 2023-06-04 20:24:53.919957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6da0a94fad8f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_context().dialect.default_schema_name != "public":
        pass
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("schema", sa.String(length=256), nullable=False),
        sa.Column("logo_path", sa.String(length=500), nullable=True),
        sa.Column("access_key", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.Column("contact", sa.String(length=500), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact"),
    )
    op.create_index(op.f("ix_users_password"), "users", ["password"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_context().dialect.default_schema_name != "public":
        pass
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_password"), table_name="users")
    op.drop_table("users")
    op.drop_table("companies")
    # ### end Alembic commands ###
